language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 2.0.0
      mono: none
    - os: osx
      osx_image: xcode8.2
      dotnet: 2.0.0
      mono: none

branches:
  only:
  - master
script:
  - dotnet test -c Release test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.TestsCore.csproj
