language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      dotnet: 1.0.1
      mono: none
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.1
      mono: none

branches:
  only:
  - master
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
install:
  - dotnet restore castle.core.asyncinterceptor.core.sln
script:
  - dotnet test -c Release -f netcoreapp1.1 test/Castle.Core.AsyncInterceptor.Tests/Castle.Core.AsyncInterceptor.TestsCore.csproj
