# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Retain the NuGet package cache between builds
cache:
  - C:\Users\appveyor\.nuget\packages

# version format
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

environment:
  COVERALLS_REPO_TOKEN:
    secure: wlbvgdxuXKnICUGjPqGoQF35j+AKryMfPyUg+YC44hcF72KnOL+ON4WkPMSvedBb

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true

# scripts that are called at very beginning, before repo cloning
init:
  # This gives the login details for the build instance so you can RDP to it.
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }

# http://blog.appveyor.com/2014/06/04/shallow-clone-for-git-repositories/
shallow_clone: true
force_https_clone: true

configuration: Release

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - dotnet restore

build_script:
  - dotnet pack src\Castle.Core.AsyncInterceptor --configuration %CONFIGURATION%

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: src\**\*.nupkg
  - path: test\TestResults

#---------------------------------#
#       tests configuration       #
#---------------------------------#

before_test:
  - dotnet build test\Castle.Core.AsyncInterceptor.Tests --configuration %CONFIGURATION%

test_script:
  - coverage.cmd %CONFIGURATION%

after_test: |
  FOR /r %%F IN (*coveralls.net.exe) DO SET coveralls_exe=%%F
  %coveralls_exe% --opencover test\TestResults\Test.Coverage.xml

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#---------------------------------#
#        global handlers          #
#---------------------------------#

#on_finish:
#  # This blocks the build server from shutting down giving time to RDP onto it to help with diagnose build issues.
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Slack
  - provider: Slack
    auth_token:
      secure: AkSNuuHmfzAFp2+Oq00NRQFOfrXl4ue08SHx0FC2WTeXSiZv8uVKI3ZBWns7HTcV
    channel: async_interceptor
    on_build_success: false
    on_build_status_changed: true
